"""empty message

Revision ID: 62603c3219b9
Revises: 
Create Date: 2025-11-21 20:38:06.574783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62603c3219b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studentsform',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('Mail_id', sa.String(length=100), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('Department', sa.String(length=100), nullable=False),
    sa.Column('college', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('studentsform')
    # ### end Alembic commands ###
